dependencies:
  - name: postgresql
    version: 8.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: platform.postgres.enabled
  - name: artifactory-ha
    version: 2.4.2
    repository: https://charts.jfrog.io/
    condition: artifactory-ha.enabled
  - name: xray
    version: 3.2.4
    repository: https://charts.jfrog.io/
    condition: xray.enabled
  - name: distribution
    version: 5.1.2
    repository: https://charts.jfrog.io/
    condition: distribution.enabled
  - name: mission-control
    version: 3.2.0
    repository: https://charts.jfrog.io/
    condition: mission-control.enabled
  - name: pipelines
    version: 1.1.1
    repository: https://charts.jfrog.io/
    condition: pipelines.enabled
