dependencies:
  - name: artifactory-ha
    version: 2.3.1
    repository: https://charts.jfrog.io/
    condition: artifactory-ha.enabled
  - name: xray
    version: 3.2.0
    repository: https://charts.jfrog.io/
    condition: xray.enabled
  - name: distribution
    version: 5.1.1
    repository: https://charts.jfrog.io/
    condition: distribution.enabled
  - name: mission-control
    version: 3.1.1
    repository: https://charts.jfrog.io/
    condition: mission-control.enabled
  - name: pipelines
    version: 1.0.36
    repository: https://charts.jfrog.io/
    condition: pipelines.enabled
